### ISSUE TITLE
How do I install it?

### ISSUE THREAD

**Issue by Phe0nyx** [asdfman/linux-shimeji#13]
It doesn't let me install a .deb version, do I just download the .zip version? Or am I doing the wrong thing?

**Comment by apoleon33** [comment]
simply do:
```bash
git clone https://github.com/asdfman/linux-shimeji.git
cd linux-shimeji        
./launch.sh
```
the shimeji will stay as long as the terminal window is open 
hop I helped you

**Comment by Phe0nyx** [comment]
Thank you! 😄
