### ISSUE TITLE
What did I do wrong?

### ISSUE THREAD

**Issue by Phe0nyx** [asdfman/linux-shimeji#14]
I was doing the following commands to launch Shimeji. Then I encountered the following:
```
invertigo_2@penguin:~$ cd linux-shimeji        
invertigo_2@penguin:~/linux-shimeji$ ./launch.sh
./launch.sh: line 1: java: command not found
```
What does it mean that the ./launch.sh command wasn't found by Java? On an Acer Chromebook with Debian 10/Buster. (By the way, invertigo2 is my name on Linux.)

**Comment by apoleon33** [comment]
I think you simply do not have Java installed on your pc
If you check, launch.sh simply launch a Java command

**Comment by apoleon33** [comment]
after check, simply do:
```bash
sudo apt update
sudo apt install default-jdk
```

**Comment by Phe0nyx** [comment]
How do I check launch.sh? I'm sorry if I don't understand.

**Comment by Phe0nyx** [comment]
I tried to launch /launch.sh , but it says this:
`-bash: ./launch.sh: No such file or directory`
Also, it hangs when I attempt to download Java. :/

**Comment by Phe0nyx** [comment]
I figured out how to get the ./launch.sh open, what next?
