### ISSUE TITLE
I figured out how to run ./launch.sh, but it didn't do anything. What now?

### ISSUE THREAD

**Issue by Phe0nyx** [asdfman/linux-shimeji#15]
./lanuch.sh showed me the code, but didn't run. What do I do next?

_Originally posted by @Phe0nyx in https://github.com/asdfman/linux-shimeji/issues/14#issuecomment-846657225_

**Comment by apoleon33** [comment]
its because you didnt launched launch.sh you simply opened it
to launch it
- check if you have java installed (#14 )
- open a terminal 
- navigate into linux-shimeji directory (using cd)
- `./launch.sh`

**Comment by Phe0nyx** [comment]
Thank you.

**Comment by apoleon33** [comment]
no problem
